### ISSUE TITLE
Good to have some common opensource guides.

### ISSUE THREAD

**Issue by Joel-hanson** [99sbr/FastAPI-Template#3]
What is the issue?
This request is not to report an issue but rather to raise an enhancement request. It would be great to have some common open source templates and guides like CONTRIBUTION.md, ISSUE_TEMPLATE.md, FEATURE_REQUEST.md.

**Comment by Joel-hanson** [comment]
@99sbr I can work on this if it's ok.

**Comment by 99sbr** [comment]
@Joel-hanson  sure
